micronaut:
  application:
    name: Library
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
---
datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
---
jpa:
  default:
    packages-to-scan:
      - 'com.alicia'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
---
libraryInfo:
  libraryName: "MOMA"
  foundedYear: "2020"
  city: "New York"
  state: "NY"
  address: "11  W 53rd St."
  country: "USA"
  zipcode:  "10019"
---
book:
  loanDurationDays: 15
